### ISSUE TITLE
[Question] How I can unregister/remove the hook?

### ISSUE THREAD

**Issue by isuke01** [Cristy94/dynamic-listener#1]
Hi,

Is there a way to remove `addDynamicEventListener` ?
I'm using SPA and I' would like to remove this EventListener on page sawap, But I'm not sure how to do it in this case :)

Thanks.

**Comment by Cristy94** [comment]
Hi,

This is a good idea, currently there is no way to remove the listener because the reference to the callback (handler) attached is not saved or return.

I think one solution would be to return the conditional handler so you can then use it with `removeEventListener`.

Something like:

```
    globalSope.addDynamicEventListener = function (rootElement, eventType, selector, callback, options) {
        var cb = getConditionalCallback(selector, callback);
        rootElement.addEventListener(eventType, cb, options);
        return cb;
    };
```

And to remove it, you could do

```
var root = document.body;
var handler = addDynamicEventListener(root, 'click', '*', () => {});
root.removeEventListener(root, handler);
```

**Comment by Cristy94** [comment]
Actually, a simpler way would be to return the unregister function, like this:

```
    globalSope.addDynamicEventListener = function (rootElement, eventType, selector, callback, options) {
        var cb = getConditionalCallback(selector, callback);
        rootElement.addEventListener(eventType, cb, options);
        return rootElement.removeEventListener.bind(globalScope, eventType, cb, options);
    };
```

Then it can be used like

```
const removeListener = addDynamicEventListener(document.body, 'click', '*', () => { console.log('Called')});
removeListener();
```

This also makes sure the listener is removed, as all the root element, callback and options must match for the `removeEventListener` to work.

**Comment by Cristy94** [comment]
Implemented this functionality (the remove callback function is now returned).
